apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wizards
  name: wizards
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wizards
  template:
    metadata:
      labels:
        app: wizards
    spec:
      containers:
      - image: reisinge/wizards
        name: wizards
        resources:
          limits:
            cpu: "250m"      # 250 millicpus
            memory: "128Mi"  # 128 mebibytes
