apiVersion: v1
kind: Service
metadata:
  labels:
    app: wizards
  name: wizards
spec:
  ports:
  - name: website-port
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: wizards
  type: {{ .Values.service.type }}