apiVersion: batch/v1
kind: Job
metadata:
  name: consumer
  labels:
    app: work-queue
    component: consumer
spec:
  # Unset completions parameter means worker-pool mode
  parallelism: 5
  template:
    metadata:
      labels:
        app: work-queue
        component: consumer
    spec:
      containers:
      - name: consumer
        image: gcr.io/kuar-demo/kuard-amd64:blue
        imagePullPolicy: Always
        command:
        - /kuard
        args:
        - --keygen-enable
        - --keygen-exit-on-complete
        - --keygen-memq-server=http://queue:8080/memq/server
        - --keygen-memq-queue=keygen
      restartPolicy: OnFailure

  
